name: Generate CSV file

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install pandas PyGithub
      - name: Generate CSV file
        run: |
          python generate_csv.py
          
      - name: Set up Git
        run: |
          git config --local user.email "saahilrawatbwr@gmail.com"
          git config --local user.name "saahilpratap"
          git config --global credential.helper store
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" > ~/.git-credentials
          chmod 0600 ~/.git-credentials
          
      - name: Commit and push CSV file to main branch
        run: |
            git add yup.csv
            git commit -m "Add generated CSV file"
            git push origin main
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
