name: Generate CSV file

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          pip install pandas PyGithub
      - name: Generate CSV file
        run: |
          python generate_csv.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
