name: Generate CSV File

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install required packages
      run: |
        pip install pandas
        pip install PyGithub

    - name: Run Python script
      run: python generate_csv.py

    - name: Save CSV file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: CSV File
        path: yup.csv
